### PR TITLE
Use Ruff as linter and formatter

### PR DESCRIPTION
**Pull request by rgonzalezfluendo**

### CODE REVIEW

**Comment by rgonzalezfluendo** [comment]
Using same configuration as [cerbero](https://github.com/GStreamer/cerbero/blob/main/.pre-commit-config.yaml)

**Review by turran — APPROVED** [review]

**Comment by turran** [comment]
I don't really see any benefit of using one or the other as there is no hard requirement here, but I'm ok with the change.

**Comment by ylatuya** [comment]
> I don't really see any benefit of using one or the other as there is no hard requirement here, but I'm ok with the change.

Ruff is fast, [very fast](https://astral.sh/blog/the-ruff-formatter).

**Comment by turran** [comment]
Yes, I'm aware; I'm saying that for the amount of code we have, the process is not slow, so for me, it is just a cosmetic change rather than a needed change.

**Comment by rgonzalezfluendo** [comment]
FYI [I also want to add ruff and pre-commit in fluster](https://github.com/fluendo/fluster/pull/161)

**Pull request merged**
